version: '3.2'

services:
  redis:
    image: redis:7.0.5-alpine
    restart: always
    ports:
      - '6379:6379'

  web:
    environment:
      - REDIS_HOST=redis
    build:
      context: .
      dockerfile: Dockerfile
    image: cassino_api
    ports:
      - "8000:8000"
    depends_on:
      - redis
