version: '3.2'

services:
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./api:/api
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    stdin_open: true
    tty: true
    # services:
    #   redis:
    #     image: redis:7.0.5-alpine
    #     restart: always
    #     ports:
    #       - '6379:6379'

    # web:
    #   restart: always
    #   environment:
    #     - REDIS_HOST=redis
    #   build:
    #     context: .
    #     dockerfile: Dockerfile
    #   # command: python manage.py runserver
    #   volumes:
    #     - ./api:/code
    #   ports:
    #     - "8000:8000"
    #   depends_on:
    #     - redis
