# Generated by Django 4.2.1 on 2023-07-07 14:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "permissions": (
                    ("add_table", "can add game table"),
                    ("remove_table", "can remove game table"),
                    ("add_player_table", "add player to exists table"),
                    ("remove_player_table", "remove player from the table"),
                )
            },
        ),
    ]
